### ISSUE TITLE
Stress test textify reddit

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#56]
**Describe the bug**
So far the bot has been subjected to a small number of posts to process at any given time. It needs to be tested to see how it responds to many requests for transcription.

**Expected behavior**
Provide many requests to the bot for transcription of images all at once to see how the bot will handle this stress case.

**Project information**
Noted that the bot had not yet handled stress tests since it's creation after the release of M4.

**Comment by afig** [comment]
Something that ended up being a pretty good test was [this comment](https://www.reddit.com/r/BDFTest/comments/be1zg9/m6_testing/el2hmat?utm_source=share&utm_medium=web2x) that requests transcription of the first ~35000 digits of pi. It identified two/three issues:

- There's no timeout for a transcription. We may want to set a limit of ~15 seconds per image in order to make sure the bot keep progressing. It takes about 2 minutes to transcribe the 35000 digits of pi on my machine. (But it may be faster if you have fewer languages installed)
- There is a limit on the number of characters in a Reddit comment: 10000. We need to make sure that our comments do not exceed this amount. Ideally, the fix would split the comment into multiple comments rather than simply throwing away anything after ~10000 characters.
- Processing the image through the bot on the remote Ubuntu I have ends up crashing the bot with the error shown below. The issue seems to be that the server runs out of RAM, which is not as big of a deal as it may seem since the server has only 512MB of RAM. For safety, we may want to say that Textify has a minimum requirement of 1GB of RAM.

```
Traceback (most recent call last):
  File "TextifyBot.py", line 177, in <module>
    processUsernameMentions(bot)
  File "TextifyBot.py", line 36, in processUsernameMentions
    processMention(newMsg)
  File "TextifyBot.py", line 58, in processMention
    result = transcribeImages(urls)
  File "TextifyBot.py", line 121, in transcribeImages
    imageText = tesseractTranscribe(imagePath)
  File "TextifyBot.py", line 102, in tesseractTranscribe
    return pytesseract.image_to_string(image)
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pytesseract/pytesseract.py", line 194, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (-9, 'Tesseract Open Source OCR Engine v3.04.01 with Leptonica')
```
